---
plugin: amazon.aws.aws_ec2
regions:
  - <type your region example eu-central-1>
filters:
  instance-state-name: running
  tag:Monitoring: enabled
keyed_groups:
  - key: tags.Environment | default('unknown')
    prefix: env
groups:
  monitored_linux: "'Monitoring' in (tags | default({}))"
  legacy_linux: "'LegacyHost' in (tags | default({}))"
compose:
  ansible_host: private_ip_address
hostnames:
  - tag:Name
  - instance-id
